# [dbo].[Account]

In [0]:
USE [PRJ301_Project ]
GO

In [0]:
/****** Object:  Table [dbo].[Account]    Script Date: 3/23/2023 8:54:38 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Account](
	[user_id] [int] IDENTITY(1,1) NOT NULL,
	[username] [varchar](50) NULL,
	[password] [varchar](10) NULL,
	[fullname] [nvarchar](50) NULL,
	[email] [nvarchar](50) NULL,
 CONSTRAINT [PK_Account] PRIMARY KEY CLUSTERED 
(
	[user_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[Blog_Detail]

In [0]:
/****** Object:  Table [dbo].[Blog_Detail]    Script Date: 3/23/2023 8:54:38 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Blog_Detail](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[category_id] [int] NULL,
	[user_id] [int] NULL,
	[title] [nvarchar](255) NULL,
	[thumbnail] [varchar](max) NULL,
	[brief] [nvarchar](max) NULL,
	[description] [nvarchar](max) NULL,
	[flag] [bit] NULL,
	[status] [bit] NULL,
	[date] [date] NULL,
	[author] [nvarchar](255) NULL,
 CONSTRAINT [PK_Blog_Detail] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

# [dbo].[Category_Blog]

In [0]:
/****** Object:  Table [dbo].[Category_Blog]    Script Date: 3/23/2023 8:54:38 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Category_Blog](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[name] [nvarchar](50) NULL,
 CONSTRAINT [PK_Category_Blog] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[Account]

In [0]:
SET IDENTITY_INSERT [dbo].[Account] ON 
INSERT [dbo].[Account] ([user_id], [username], [password], [fullname], [email]) VALUES (5, N'JohnDoe', N'123', N'John Doe', N'johndoe@example.com')
INSERT [dbo].[Account] ([user_id], [username], [password], [fullname], [email]) VALUES (7, N'JohnDoe', N'word123', N'John Doe', N'johndoe@example.com')
INSERT [dbo].[Account] ([user_id], [username], [password], [fullname], [email]) VALUES (8, N'JaneDoe', N'abc123', N'Jane Doe', N'janedoe@example.com')
INSERT [dbo].[Account] ([user_id], [username], [password], [fullname], [email]) VALUES (9, N'BobSmith', N'qwerty', N'Bob Smith', N'bobsmith@example.com')
INSERT [dbo].[Account] ([user_id], [username], [password], [fullname], [email]) VALUES (10, N'system123', NULL, N'Luong Thi Quyen', N'quyenlt08012001@gmail.com')
INSERT [dbo].[Account] ([user_id], [username], [password], [fullname], [email]) VALUES (11, N'nam', NULL, N'nguyen hai nam', N'tuanqwee@gmail.com')
INSERT [dbo].[Account] ([user_id], [username], [password], [fullname], [email]) VALUES (12, N'hainam1', NULL, N'nguyen hai nam', N'langtukotien1994@yahoo.com.vn')
INSERT [dbo].[Account] ([user_id], [username], [password], [fullname], [email]) VALUES (13, N'tuan', NULL, N'tuan', N'langtukotien1994@yahoo.com.vn')
INSERT [dbo].[Account] ([user_id], [username], [password], [fullname], [email]) VALUES (14, N'minhtuan2', NULL, N'nguyen hai nam', N'tuanqwee@gmail.com')
INSERT [dbo].[Account] ([user_id], [username], [password], [fullname], [email]) VALUES (15, N'minhtuan2', N'123', N'nguyen minh tuan ', N'nguyenminhtuanqwee@gmail.com')
INSERT [dbo].[Account] ([user_id], [username], [password], [fullname], [email]) VALUES (16, N'minhtuan2', N'12345', N'nguyen minh tuan ', N'nguyenminhtuanqwee@gmail.com')
INSERT [dbo].[Account] ([user_id], [username], [password], [fullname], [email]) VALUES (17, N'minhtuan2', N'123', N'nguyen minh tuan ', N'nguyenminhtuanqwee@gmail.com')
INSERT [dbo].[Account] ([user_id], [username], [password], [fullname], [email]) VALUES (18, N'minhtuan2', N'123', N'nguyen minh tuan ', N'nguyenminhtuanqwee@gmail.com')
INSERT [dbo].[Account] ([user_id], [username], [password], [fullname], [email]) VALUES (19, N'minhtuan2', N'123', N'nguyen minh tuan ', N'nguyenminhtuanqwee@gmail.com')
INSERT [dbo].[Account] ([user_id], [username], [password], [fullname], [email]) VALUES (20, N'pocanut', N'123', N'nguyen hai nam', N'langtukotien1994@yahoo.com.vn')
INSERT [dbo].[Account] ([user_id], [username], [password], [fullname], [email]) VALUES (21, N'minhtuan2', N'123', N'nguyen minh tuan ', N'nguyenminhtuanqwee@gmail.com')
INSERT [dbo].[Account] ([user_id], [username], [password], [fullname], [email]) VALUES (22, N'minhtuan2', N'123', N'nguyen minh tuan ', N'nguyenminhtuanqwee@gmail.com')
INSERT [dbo].[Account] ([user_id], [username], [password], [fullname], [email]) VALUES (23, N'minhtuan', N'123', N'nguyenminhtuan', N'nguyenminhtuanqwee@gmail.com')
INSERT [dbo].[Account] ([user_id], [username], [password], [fullname], [email]) VALUES (24, N'minhtuan3', N'12345', N'nguyen minh tuan ', N'nguyenminhtuanqwee@gmail.com')
INSERT [dbo].[Account] ([user_id], [username], [password], [fullname], [email]) VALUES (25, N'minhtuan3', N'12345', N'nguyenminhtuan', N'nguyenminhtuanqwee@gmail.com')
INSERT [dbo].[Account] ([user_id], [username], [password], [fullname], [email]) VALUES (26, N'minhtuan3', N'123', N'nguyenminhtuan', N'nguyenminhtuanqwee@gmail.com')
INSERT [dbo].[Account] ([user_id], [username], [password], [fullname], [email]) VALUES (27, N'minhtuan4', N'123', N'nguyen minh tuan ', N'nguyenminhtuanqwee@gmail.com')
INSERT [dbo].[Account] ([user_id], [username], [password], [fullname], [email]) VALUES (28, N'minhtuan4', N'12345', N'nguyen minh tuan ', N'nguyenminhtuanqwee@gmail.com')
INSERT [dbo].[Account] ([user_id], [username], [password], [fullname], [email]) VALUES (29, N'minhtuan5', N'12345', N'nguyen minh anh', N'nguyenminhtuanqwee@gmail.com')
INSERT [dbo].[Account] ([user_id], [username], [password], [fullname], [email]) VALUES (30, N'minhtuan5', N'12345', N'nguyen minh tuan ', N'nguyenminhtuanqwee@gmail.com')
INSERT [dbo].[Account] ([user_id], [username], [password], [fullname], [email]) VALUES (31, N'minhtuan5', N'12345', N'nguyenminhtuan', N'nguyenminhtuanqwee@gmail.com')
INSERT [dbo].[Account] ([user_id], [username], [password], [fullname], [email]) VALUES (32, N'minhtuan5', N'1234', N'nguyen minh tuan ', N'nguyenminhtuanqwee@gmail.com')
INSERT [dbo].[Account] ([user_id], [username], [password], [fullname], [email]) VALUES (33, N'minhtuan6', N'123456', N'nguyen minh anh', N'nguyenminhtuanqwee@gmail.com')
INSERT [dbo].[Account] ([user_id], [username], [password], [fullname], [email]) VALUES (34, N'minhtuan6', N'123456', N'nguyen minh anh', N'nguyenminhtuanqwee@gmail.com')
INSERT [dbo].[Account] ([user_id], [username], [password], [fullname], [email]) VALUES (35, N'minhtuan7', N'13243243', N'nguyen minh tuan ', N'nguyenminhtuanqwee@gmail.com')
INSERT [dbo].[Account] ([user_id], [username], [password], [fullname], [email]) VALUES (36, N'minhtuan7', N'13243243', N'nguyen minh tuan ', N'nguyenminhtuanqwee@gmail.com')
INSERT [dbo].[Account] ([user_id], [username], [password], [fullname], [email]) VALUES (37, N'minhtuan7', N'13243243', N'nguyen minh tuan ', N'nguyenminhtuanqwee@gmail.com')
INSERT [dbo].[Account] ([user_id], [username], [password], [fullname], [email]) VALUES (38, N'minhtuan7', N'13243243', N'nguyen minh tuan ', N'nguyenminhtuanqwee@gmail.com')
INSERT [dbo].[Account] ([user_id], [username], [password], [fullname], [email]) VALUES (39, N'minhtuan7', N'13243243', N'nguyen minh tuan ', N'nguyenminhtuanqwee@gmail.com')
INSERT [dbo].[Account] ([user_id], [username], [password], [fullname], [email]) VALUES (40, N'pocanut', N'123124342', N'nguyen minh tuan ', N'nguyenminhtuanqwee@gmail.com')
INSERT [dbo].[Account] ([user_id], [username], [password], [fullname], [email]) VALUES (42, N'minhtuan123', N'1234', N'nguyen minh tuan ', N'nguyenminhtuanqwee@gmail.com')
INSERT [dbo].[Account] ([user_id], [username], [password], [fullname], [email]) VALUES (43, N'pocanut', N'123', N'nguyen hai nam', N'nguyenducquang12a3vn@gmail.com')
SET IDENTITY_INSERT [dbo].[Account] OFF
GO

# [dbo].[Blog_Detail]

In [0]:
SET IDENTITY_INSERT [dbo].[Blog_Detail] ON 
INSERT [dbo].[Blog_Detail] ([id], [category_id], [user_id], [title], [thumbnail], [brief], [description], [flag], [status], [date], [author]) VALUES (4, 1, 1, N'Học sinh THPT Phạm Ngũ Lão hân hoan ngày trở lại trường', N'https://tapchigiambeo.com/wp-content/uploads/2019/03/thuc-don-giam-can-cho-hoc-sinh-cap-tapchi.jpg', N'This is the first blog post', N'Không còn phải học online qua màn hình máy tính, các bạn học sinh đã được quay trở lại nhịp học tập bình thường tại trường trong tâm trạng háo hức, phấn khởi. Trường THPT Phạm Ngũ Lão vận hành bởi CEO High School, ngôi trường cấp 3 theo định hướng doanh nhân tại Hà Nội đặc biệt chuẩn bị kỹ lưỡng các công tác đón học sinh, tuân thủ quy định phòng chống dịch giúp phụ huynh an tâm hơn.', 1, 1, CAST(N'2023-03-21' AS Date), N'tin tuc 24H')
INSERT [dbo].[Blog_Detail] ([id], [category_id], [user_id], [title], [thumbnail], [brief], [description], [flag], [status], [date], [author]) VALUES (5, 1, 1, N'Vì sao học sinh lớp 1 đến lớp 6 chưa có lộ trình học?', N'https://kenh14cdn.com/thumb_w/620/203336854389633024/2022/1/13/photo-1-1642071932296514557361.jpg', N'This is the second blog post', N'"Trên thực tế có trường hợp các cơ sở thiếu giáo viên, bảo mẫu. Tuy nhiên, phụ huynh nên yên tâm bởi vẫn còn thời gian để chuẩn bị nhân sự. Sau Tết, các cơ sở có thể mời các thầy cô quay trở lại làm việc. Bên cạnh đó, TP.HCM cũng đã có kế khoach bổ sung nhân sự, tuyển giáo viên. Sở GD-ĐT sẽ tham mưu UBND quận, huyện trong việc tuyển giáo viên cho các cơ sở còn thiếu" - ông Trọng cho hay.

Ông Trọng cho biết thêm, học sinh đi học trên cơ sở đồng thuận của phụ huynh và cơ sở giáo dục phải đáp ứng đảm bảo an toàn. An toàn tới đâu cơ sở mầm non đón trẻ tới đó.

Thông tin về việc hiện TP.HCM đã là "vùng xanh", vậy các cơ sở giáo dục có cần đảm bảo giãn cách trong dạy và học, ông Trọng cho biết ngay từ khi khởi động cho học sinh lớp 9 và 12 đến trường học trực tiếp, các cơ sở giáo dục đã có những hoạt động như mở căn tin, học bán trú. Tuy nhiên, khi hoạt động phải đảm bảo công tác phòng chống dịch trong dạy và học.', 1, 0, CAST(N'2023-03-16' AS Date), N'Jane Smith')
INSERT [dbo].[Blog_Detail] ([id], [category_id], [user_id], [title], [thumbnail], [brief], [description], [flag], [status], [date], [author]) VALUES (6, 2, 1, N'Trường không kịp tổ chức bán trú, học sinh chưa có đồng phục trong ngày tựu trường', N'https://kenh14cdn.com/thumb_w/620/203336854389633024/2022/4/6/photo-1-16492154642941633248808.jpg', N'This is the third blog post', N'Còn chị Trần Thu Thuỷ, có con học lớp 5, Trường tiểu học Đặng Trần Côn, quận Thanh Xuân cho biết, sáng nay con mặc quần áo bình thường, nhà trường không yêu cầu học sinh mặc đồng phục. “Đêm hôm trước, con có háo hức, tìm lại đồng phục nhưng cái thì bẩn, cái quá cũ, ngắn không mặc được. Chị cũng quyết định không mua mới vì chỉ còn vài tháng nữa kết thúc năm học”, chị Thuỷ nói.

Một phụ huynh khác có con học lớp 1 cho hay, trong thông báo gửi tới cha mẹ học sinh không yêu cầu các con mặc đồng phục. “Tuy nhiên, chiều qua, con sang nhà hàng xóm thấy các bạn có đồng phục về đòi mẹ, không có con đã khóc. Những lần trước cũng chuẩn bị đi học sau đó lại dừng nên lần này con cứ hỏi đi hỏi lại mẹ có chắc chắn không? Mẹ không được nói dối con nữa nhé”, phụ huynh này nói.', 1, 1, CAST(N'2023-03-14' AS Date), N'tin tuc 24H')
INSERT [dbo].[Blog_Detail] ([id], [category_id], [user_id], [title], [thumbnail], [brief], [description], [flag], [status], [date], [author]) VALUES (7, 1, 1, N'Thi tuyển lớp 10: Hà Nội sẽ công bố môn thi vào tháng 3/2022', N'https://kenh14cdn.com/thumb_w/620/203336854389633024/2022/1/18/6a-1318-587-1642504673403373511909.jpeg', N'Brief 1', N'Tại Hội nghị sơ kết học kỳ I, triển khai nhiệm vụ học kỳ II năm học 2021-2022 cấp THCS theo hình thức trực tuyến sáng nay (18/1), Phó Giám đốc Sở GD&ĐT Phạm Xuân Tiến cho biết, có một số ý kiến đề xuất công bố sớm môn thi thứ tư của kỳ thi tuyển sinh lớp 10 năm học 2022-2023. Tuy nhiên, tháng 3 hằng năm Sở GD&ĐT mới công bố môn thi thứ 4 là quy định đã được duy trì trong những năm gần đây. Trước đó, học sinh đã xác định được 3 môn thi gồm: Toán, Ngữ văn, Ngoại ngữ', 1, 0, CAST(N'2023-03-15' AS Date), N'tin tuc 24H')
INSERT [dbo].[Blog_Detail] ([id], [category_id], [user_id], [title], [thumbnail], [brief], [description], [flag], [status], [date], [author]) VALUES (8, 1, 1, N'CHÍNH THỨC: Lịch đi học trở lại sau Tết Quý Mão 2023 của học sinh cả nước', N'https://kenh14cdn.com/thumb_w/620/203336854389633024/2023/1/25/photo-1-1674710671696518987005.jpg', N'Brief 2', N'Theo lãnh đạo của nhiều cơ sở giáo dục, đến nay, việc dạy học trực tiếp tại trường gần như diễn ra bình thường, các trường tăng dần số lượng HS và thời lượng học trực tiếp ở tất cả các môn. Theo ông Hà Thanh Hải, Phó trưởng Phòng Giáo dục và Đào tạo (GD-ĐT) quận 7, đến nay, tỉ lệ HS trở lại trường ở các bậc học đều đạt trên 70%. Trường lớp và đội ngũ giáo viên (GV) đều có thể đáp ứng nếu HS trở lại trường cùng một thời điểm tăng cao. "Đội ngũ GV đã tiêm vắc-xin đầy đủ và có nhiều kinh nghiệm trong phòng chống dịch, xử lý các tình huống phát sinh. Tuy nhiên, để bảo đảm an toàn, các trường vẫn phải thường xuyên khử khuẩn, yêu cầu HS đeo khẩu trang, GV quan sát HS để kịp thời xử trí các trường hợp nghi ngờ có triệu chứng" - ông Hải nói', 1, 1, CAST(N'2023-03-14' AS Date), N'tin tuc 24H')
INSERT [dbo].[Blog_Detail] ([id], [category_id], [user_id], [title], [thumbnail], [brief], [description], [flag], [status], [date], [author]) VALUES (9, 1, 1, N'Hôm nay (22/8), hơn 1,9 triệu học sinh lớp 1 tựu trường', N'https://kenh14cdn.com/thumb_w/620/203336854389633024/2022/3/4/photo-1-1646365956085959940052.jpeg', N'Brief 3', N'Hôm nay, hơn 1,9 triệu học sinh lớp 1 trên cả nước chính thức tựu trường. Đón học sinh đi học trở lại, các trường đều tăng cường rà soát các điều kiện cơ sở vật chất như đường điện, ống nước, bàn ghế, cầu thang, quạt điện… nhằm đảm bảo an toàn cho học sinh, phòng tránh tai nạn thương tích.

Theo kế hoạch năm học 2022-2023 đối với giáo dục mầm non, phổ thông và giáo dục thường xuyên được Bộ Giáo dục và Đào tạo ban hành ngày 5/8, khai giảng năm học mới diễn ra vào ngày 5/9 như mọi năm.', 0, 1, CAST(N'2023-03-14' AS Date), N'tin tuc 24H')
INSERT [dbo].[Blog_Detail] ([id], [category_id], [user_id], [title], [thumbnail], [brief], [description], [flag], [status], [date], [author]) VALUES (10, 1, 1, N'Nóng: Hà Nội tạm dừng việc tới trường của học sinh từ lớp 1 đến lớp 6 trên địa bàn 12 quận', N'https://kenh14cdn.com/thumb_w/620/203336854389633024/2022/8/21/b24b96faf5be30e069af-8018-1661117401245574078349.jpg', N'Bài viết số 1', N'Chiều 18/2, Sở GD&ĐT Hà Nội đã gửi Tờ trình số 397/TTr-SGDĐT đến UBND TP Hà Nội để đề xuất tạm dừng phương án cho học sinh các khối lớp 1, 2, 3, 4, 5, 6 thuộc 12 quận trở lại trường học trực tiếp (theo công văn số 432/UBND-KGVX ban hành ngày 15/2).

Lý do là tình hình dịch Covid-19 trên địa bàn thành phố vẫn diễn biến phức tạp, số ca lây nhiễm trong cộng đồng có xu hướng tăng. Kèm với đó, theo dự báo của Trung tâm Khí tượng Thủy văn quốc gia, tuần tới sẽ có đợt không khí lạnh với cường độ mạnh gây rét đậm, rét hại ảnh hưởng đến khu vực Hà Nội khiến nhiều cha mẹ học sinh còn băn khoăn lo lắng khi cho con tới trường. Tỷ lệ đồng thuận của cha mẹ học sinh chưa cao trong việc cho con em trở lại trường học trực tiếp.', 1, 0, CAST(N'2023-03-15' AS Date), N'tin tuc 24H')
INSERT [dbo].[Blog_Detail] ([id], [category_id], [user_id], [title], [thumbnail], [brief], [description], [flag], [status], [date], [author]) VALUES (12, 1, 1, N'Hiệu trưởng Hà Nội đề xuất cho học sinh đến trường từ tháng 8: Nhiều ý kiến trái chiều', N'https://kenh14cdn.com/thumb_w/620/203336854389633024/2022/4/14/photo-1-16499043281101931129895.jpg', N'fsdfds', N'Khung kế hoạch thời gian năm học 2021 - 2022 của Bộ GD&ĐT quy định, các địa phương hoàn thành kế hoạch giáo dục học kỳ II trước 25/5 và kết thúc năm học vào cuối tháng.

Tuy nhiên, trong đó, Bộ GD&ĐT cũng quy định, Chủ tịch UBND cấp tỉnh quyết định kế hoạch thời gian năm học đối với giáo dục mầm non, phổ thông và giáo dục thường xuyên phù hợp với thực tiễn địa phương.

Khác với những đợt bùng dịch COVID-19 trước, năm học này, nhiều địa phương bị ảnh hưởng trầm trọng đến kế hoạch dạy học trực tiếp. Đơn cử như TP.HCM, học sinh lớp 1-6 đến trường học trực tiếp từ ngày 14/2. Tại Hà Nội, học sinh tiểu học cũng nghỉ hè, học trực tuyến trọn vẹn 11 tháng, vừa trở lại trường học từ 6/4.', 1, 1, CAST(N'2023-03-14' AS Date), N'tin tuc 24H')
INSERT [dbo].[Blog_Detail] ([id], [category_id], [user_id], [title], [thumbnail], [brief], [description], [flag], [status], [date], [author]) VALUES (13, 1, 1, N'CHÍNH THỨC: Lịch đi học trở lại sau Tết Quý Mão 2023 của học sinh cả nước', N'https://kenh14cdn.com/thumb_w/620/203336854389633024/2022/1/18/6a-1318-587-1642504673403373511909.jpeg', N'', N'Như thông báo đã đưa, hầu hết các tỉnh/ thành phố trên cả nước sẽ cho học sinh các cấp đi học trở lại sớm nhất vào ngày 27/1 (tức mùng 6 Tết) và muộn nhất vào ngày 30/1 (tức mùng 9 Tết).', 1, 1, CAST(N'2023-03-14' AS Date), N'tin tuc 24H')
INSERT [dbo].[Blog_Detail] ([id], [category_id], [user_id], [title], [thumbnail], [brief], [description], [flag], [status], [date], [author]) VALUES (14, 1, 1, N'TP.HCM có 7.500 học sinh Tiểu học rút học bạ về quê', N'https://kenh14cdn.com/thumb_w/620/203336854389633024/2022/1/10/photo-1-164181780320544205925.jpg', N'ẻwqr', N'"Việc đi học phải theo chỉ đạo của UBND TP.HCM, riêng đối với học sinh lớp 6, Sở Giáo dục và Đào tạo đang tham mưu cho TP để cho học sinh trở lại trường trong thời gian tới" - ông Trọng nói.

Việc tổ chức dạy trực tiếp theo cấp độ dịch sẽ thay đổi hình thức tổ chức dạy học, Sở GD-ĐT sẽ triển khai các văn bản ngay từ đầu. Khi TP thay đổi cấp độ dịch Covid-19, các cơ sở giáo dục sẽ thay đổi hình thức học tương ứng. Điều này thể hiện sự linh hoạt trong việc dạy và học ở thời điểm phòng, chống dịch bệnh.

Ngoài ra, việc học sinh đi học trở lại phụ thuộc vào nhiều tiêu chí chứ không chỉ là tiêm vắc-xin. Hiện Sở đã tham mưu và báo cáo để mở rộng dạy trực tiếp cho các khối lớp khác. Tuy nhiên, kế hoạch sẽ phụ thuộc vào quyết định của UBND TP.', 1, 1, CAST(N'2023-03-14' AS Date), N'tin tuc 24H')
INSERT [dbo].[Blog_Detail] ([id], [category_id], [user_id], [title], [thumbnail], [brief], [description], [flag], [status], [date], [author]) VALUES (15, 3, 1, N'Các trường THPT tại Hà Nội chuẩn bị gì để đón học sinh đi học trực tiếp vào tuần tới?', N'https://kenh14cdn.com/thumb_w/620/203336854389633024/2021/12/1/photo-1-1638324028541303574755.jpeg', N'drf', N'Nói về việc đón học sinh quay lại trường, thầy Nguyễn Công Sở - Hiệu trưởng THPT Lê Văn Thiêm (quận Long Biên, Hà Nội) cho biết thời gian kết thúc học kỳ I sắp đến, đây là kỳ kiểm tra rất quan trọng của học sinh nên thầy đề xuất được chủ động thời gian trong việc đón các em quay lại trường để đảm bảo quá trình ôn tập cũng như kiểm tra học kỳ I của học sinh đạt kết quả tốt nhất.

“Học sinh quay lại trường là điều mong mỏi không chỉ của phía học sinh, phụ huynh mà cả giáo viên, nhưng việc đảm bảo an toàn đón học sinh quay lại trường mới là điều quan trọng, nhất trong tình hình hiện tại Hà Nội ghi nhận nhiều F0 cộng đồng.

Về cơ sở vật chất đón học sinh quay lại, trường chúng tôi cũng đã tiến khử khuẩn, lên phương án dạy học giãn cách....

Hiện giáo viên tại THPT Lê Văn Thiêm đã được tiêm 100% đủ cả hai mũi vắc xin và học sinh cũng được tiêm 100% mũi 1”, thầy Sở nói.', 1, 1, CAST(N'2023-03-14' AS Date), N'tin tuc 24H')
INSERT [dbo].[Blog_Detail] ([id], [category_id], [user_id], [title], [thumbnail], [brief], [description], [flag], [status], [date], [author]) VALUES (16, 2, 1, N'Phó Thủ tướng Vũ Đức Đam: Mở cửa trường học an toàn, linh hoạt, thống nhất cả nước', N'https://kenh14cdn.com/thumb_w/620/203336854389633024/2022/2/18/photo-1-16451772158441802284310.jpg', N'ãưfds', N'Quy trình xử lý tại các cơ sở giáo dục khi phát hiện các trường hợp học sinh F0; F1 tại gia đình hoặc trường học chưa thống nhất, còn lúng túng. Việc khoanh vùng xác định F1 chưa hợp lý dẫn đến nhiều học sinh phải nghỉ học trên lớp, chuyển sang học trực tuyến vì trong lớp có F0. Cá biệt có nơi cho cả lớp hoặc cả khối dừng học trực tiếp khi phát hiện F0 trong một lớp.

Khi tổ chức đưa học sinh đi học trực tiếp trở lại, có địa phương yêu cầu 100% học sinh phải xét nghiệm COVID-19, phần lớn kinh phí do phụ huynh chi trả gây phản ứng không cần thiết. Nhiều địa phương chưa tổ chức dạy học bán trú cho học sinh nên gây bức xúc, khó khăn cho phụ huynh và xã hội trong việc sắp xếp thời gian đưa đón con.

Bên cạnh đó, nhân lực y tế trường học còn thiếu và yếu ở nhiều địa phương dẫn đến phải huy động hầu hết cán bộ, giáo viên kiêm nhiệm công tác phòng, chống dịch. Kinh phí cho việc mua sắm thiết bị phòng, chống dịch trong các cơ sở giáo và vệ sinh khử khuẩn còn thiếu.', 1, 1, CAST(N'2023-03-14' AS Date), N'tin tuc 24H')
INSERT [dbo].[Blog_Detail] ([id], [category_id], [user_id], [title], [thumbnail], [brief], [description], [flag], [status], [date], [author]) VALUES (17, 2, 1, N'Phụ huynh phản ứng vì phải chi trả phí xét nghiệm Covid-19 trước khi con đến trường', N'https://kenh14cdn.com/thumb_w/620/203336854389633024/2022/2/17/photo-1-16450977366482085823168.jpg', N'èwe', N'Cuộc họp có sự tham dự của Bộ trưởng Bộ Giáo dục và Đào tạo (GD-ĐT), lãnh đạo Ban Tuyên giáo Trung ương, lãnh đạo Ủy ban Văn hóa, Giáo dục của Quốc hội, lãnh đạo các Bộ: Quốc phòng, Công an, Y tế, Thông tin và Truyền thông, Lao động, Thương binh và Xã hội, Giao thông Vận tải, Văn phòng Chính phủ… Tại điểm cầu 63 tỉnh, thành sẽ có sự tham dự của lãnh đạo UBND các tỉnh, thành, lãnh đạo Sở GD-ĐT, Sở Y tế và các đơn vị liên quan của địa phương.

Theo báo cáo của Bộ GD-ĐT, đến ngày 16-2, tổng số học sinh học trực tiếp trên cả nước là 21.001.019/22.409.817, tỉ lệ 93,71%.

54/63 tỉnh, thành phố đã tổ chức cho toàn bộ trẻ mầm non học trực tiếp (tỉnh Nam Định: TP Nam Định trẻ mầm non chưa tổ chức) (09 tỉnh, thành phố chưa tổ chức gồm: Hậu Giang, Trà Vinh, Hưng Yên, Vĩnh Long, Hà Nội, Phú Yên, Đà Nẵng, An Giang, Tiền Giang).', 1, 1, CAST(N'2023-03-14' AS Date), N'tin tuc 24H')
INSERT [dbo].[Blog_Detail] ([id], [category_id], [user_id], [title], [thumbnail], [brief], [description], [flag], [status], [date], [author]) VALUES (20, 3, 1, N'Đồng Nai: Khen thưởng 2 học sinh trả lại của rơi hơn 100 triệu đồng', N'https://images2.thanhnien.vn/thumb_w/640/528068263637045248/2023/3/22/edit-zalo-11-1679485625618365027739.png', N'thanh nien ', N'Chiều 22.3, Sở GD-ĐT Đồng Nai đã đến Trường tiểu học Phú Ngọc B (xã Phú Ngọc, H.Định Quán, Đồng Nai) để khen thưởng đột xuất 2 em Lê Nhã Trâm và Nguyễn Quốc Kỳ (học sinh lớp 5) vì có hành động đẹp nhặt được của rơi trả lại người đánh mất', 1, 1, CAST(N'2023-03-23' AS Date), N'Bao24H')
SET IDENTITY_INSERT [dbo].[Blog_Detail] OFF
GO

# [dbo].[Category_Blog]

In [0]:
SET IDENTITY_INSERT [dbo].[Category_Blog] ON 
INSERT [dbo].[Category_Blog] ([id], [name]) VALUES (1, N'C1')
INSERT [dbo].[Category_Blog] ([id], [name]) VALUES (2, N'C2')
INSERT [dbo].[Category_Blog] ([id], [name]) VALUES (3, N'C3')
SET IDENTITY_INSERT [dbo].[Category_Blog] OFF
GO